import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("admin research briefs section is admin-only and exposed in admin navigation", () => {
  const page = read("app/admin/research-briefs/page.tsx");
  const panel = read("components/admin/AdminSettingsPanel.tsx");

  assert.match(page, /VerifiedSessionGuard[\s\S]*requireAdmin/);
  assert.match(page, /initialTab="research_briefs"/);
  assert.match(panel, /label: "Research Briefs"/);
  assert.match(panel, /<AdminResearchBriefGeneratorView showToast=\{showToast\} \/>/);
});

test("research brief generator uses Responses-backed admin APIs and defaults to drafts", () => {
  const component = read("components/admin/AdminResearchBriefGeneratorView.tsx");
  const api = read("lib/api.ts");

  assert.match(component, /Generate Draft/);
  assert.match(component, /Save Draft/);
  assert.match(component, /Ready for Review/);
  assert.match(component, /Title/);
  assert.match(component, /Insights card title/);
  assert.match(component, /Short title for Insights cards/);
  assert.match(component, /updateSuggestedCard/);
  assert.match(component, /onSuggestedCardChange\(\{ title: event\.target\.value \}\)/);
  assert.match(component, /onSuggestedCardChange\(\{ description: event\.target\.value \}\)/);
  assert.match(component, /Insights preview body/);
  assert.match(component, /Full post body/);
  assert.match(component, /Advanced metadata/);
  assert.match(component, /Model/);
  assert.match(component, /GPT-5\.6 Luna/);
  assert.match(component, /GPT-5\.6 Terra/);
  assert.match(component, /GPT-5\.6 Sol/);
  assert.match(component, /External research mode/);
  assert.match(component, /Generate thumbnail \/ hero image/);
  assert.match(component, /Section format/);
  assert.match(component, /Walnut confirmation score/);
  assert.match(component, /Include Walnut&apos;s proprietary confirmation score, shown separately from underlying data\./);
  assert.match(component, /updateConfig\("include_confirmation_score", event\.target\.checked\)/);
  assert.match(component, /Cross-source confirmations/);
  assert.match(component, /Mention which data categories support or contradict the thesis\./);
  assert.match(component, /Add source URL manually/);
  assert.match(component, /manual_source_url: ""/);
  assert.match(component, /updateConfig\("manual_source_url", event\.target\.value\)/);
  assert.match(component, /Use when official source discovery misses a company earnings release or filing\./);
  assert.match(component, /Source discovery/);
  assert.match(component, /Official earnings release/);
  assert.match(component, /Primary ticker context match/);
  assert.match(component, /include_confirmation_score: false/);
  assert.match(component, /include_cross_source_confirmations: false/);
  assert.match(component, /updateConfig\("include_cross_source_confirmations", event\.target\.checked\)/);
  assert.match(component, /WALNUT_CALL_VALUES/);
  assert.match(component, /Bullish but expensive/);
  assert.match(component, /Mixed with capex risk/);
  assert.match(component, /Insufficient data to make a call/);
  assert.match(component, /Walnut call must use the approved expanded call taxonomy\./);
  assert.match(component, /walnutCallInvalid \|\| blockingWarnings/);
  assert.match(component, /articleDraft\?\.walnut_call/);
  assert.match(component, /Comparison tickers/);
  assert.match(component, /placeholder="GOOGL, AMZN, MSFT"/);
  assert.match(component, /Separate multiple tickers with commas\./);
  assert.match(component, /parseComparisonTickers/);
  assert.match(component, /comparison_tickers: normalizedComparisonTickers/);
  assert.match(component, /removeComparisonTicker/);
  assert.match(component, /is not currently supported as a comparison ticker/);
  assert.match(component, /startAdminResearchBriefGeneration/);
  assert.match(component, /getAdminResearchBriefGenerationJob/);
  assert.match(component, /getAdminResearchBriefGenerationDraft/);
  assert.match(component, /getAdminResearchBriefDraft/);
  assert.match(component, /setSelectedDraft\(nextSelected\)/);
  assert.match(component, /setDrafts\(items\)/);
  assert.match(component, /function applySavedDraft\(draft: AdminResearchBriefDraft\)/);
  assert.match(component, /applySavedDraft\(draft\);[\s\S]*Draft saved\./);
  assert.doesNotMatch(component, /const draft = await updateAdminResearchBriefDraft\(selectedDraft\.id, \{ status, article \}\);[\s\S]{0,120}await refreshDrafts\(draft\)/);
  assert.match(component, /saveDraft\(selectedDraft\?\.status === "published" \? "published" : "draft"\)/);
  assert.match(component, /Save Published Changes/);
  assert.match(component, /const savedDraft = await updateAdminResearchBriefDraft\(selectedDraft\.id, \{ article \}\);[\s\S]*publishAdminResearchBriefDraft\(savedDraft\.id\)/);
  assert.match(component, /Draft saved and published\./);
  assert.match(component, /Generating research brief/);
  assert.match(component, /researchBriefJobTimedOut/);
  assert.match(component, /Research brief generation timed out/);
  assert.match(component, /generationJobActive/);
  assert.match(component, /Research brief generation failed\. Try again or reduce research depth\./);
  assert.match(component, /Research brief generated, but the draft could not be loaded yet/);
  assert.match(api, /comparison_tickers: string\[\]/);
  assert.match(api, /AdminResearchBriefJob/);
  assert.match(api, /\/api\/admin\/research-briefs\/jobs\/\$\{encodeURIComponent\(jobId\)\}/);
  assert.match(component, /Reddit DD - Issue \/ Risk \/ Data \/ Conclusion/);
  assert.match(component, /Find Sources \/ Refresh Research/);
  assert.match(component, /This draft has no source links/);
  assert.doesNotMatch(component, /window\.confirm\("Publish this research brief/);
  assert.match(component, /PublishDraftDialog/);
  assert.match(component, /Double-check the confirmation score with the admin account before publishing because it was updated manually\./);
  assert.doesNotMatch(component, /window\.prompt\("Type DELETE/);
  assert.match(component, /DeleteDraftDialog/);
  assert.match(component, /Destructive action/);
  assert.match(component, /Type <span className="font-semibold text-white">DELETE<\/span> to confirm/);
  assert.match(component, /placeholder="Type DELETE"/);
  assert.match(component, /include_charts: false/);
  assert.match(api, /include_confirmation_score: boolean/);
  assert.match(api, /include_cross_source_confirmations: boolean/);
  assert.match(api, /manual_source_url\?: string \| null/);
  assert.match(api, /source_discovery\?: Record<string, unknown>/);
  assert.match(api, /walnut_call\?: string/);
  assert.match(api, /confirmation_score_included\?: boolean/);
  assert.match(api, /refresh-sources/);
  assert.match(api, /\/api\/admin\/research-briefs\/generate/);
  assert.match(api, /publication_default/);
});

test("public research brief integration preserves existing MU brief", () => {
  const registry = read("lib/researchBriefs.ts");
  const section = read("components/insights/ResearchBriefsSection.tsx");
  const generatedPage = read("app/research/[slug]/page.tsx");

  assert.match(registry, /slug: "mu-dd"/);
  assert.match(registry, /route: "\/research\/mu-dd"/);
  assert.match(section, /getPublishedResearchBriefs/);
  assert.match(section, /getGeneratedResearchBriefCards/);
  assert.match(section, /!seen\.has\(brief\.slug\)/);
  assert.match(generatedPage, /GeneratedResearchBriefPage/);
});
