import Link from "next/link";
import type { ReactNode } from "react";
import type { DepartmentsOverviewResponse, ProfileMetric, ProfileSectorPeriod } from "@/lib/api";

type Row = Record<string, unknown>;
type CellFormat = "currency" | "number" | "percent" | "date" | "link";
type TableSpec = { title: string; rows: Row[]; columns: Array<[string, string, CellFormat?]>; cta?: { href: string; label: string } };

const COLORS = ["#42d3a7", "#3b82f6", "#a855f7", "#f6b91a", "#fb7185", "#60a5fa", "#a3e635", "#94a3b8"];

export function EnhancedGovernmentDashboard({ data, periodFilter }: { data: DepartmentsOverviewResponse; periodFilter: ReactNode }) {
  const comparison = data.comparison?.label || `previous ${data.period_days} days`;
  const comparisonPaused = data.comparison?.status && data.comparison.status !== "ok";
  const active = data.most_active_departments[0];
  const largest = data.largest_recent_awards[0];
  const growing = data.fastest_growing_vendors[0];
  const latestSectors = data.contract_value_over_time[data.contract_value_over_time.length - 1]?.segments ?? [];
  const topSector = latestSectors[0];
  const contractMetric = findMetric(data.summary, "Total Contracts");
  const modificationMetric = findMetric(data.summary, "Contract Modifications");
  const trends = data.contract_value_over_time.map((row) => ({ label: row.period, value: row.segments.reduce((sum, segment) => sum + segment.value, 0) }));

  return <main className="relative min-w-0 space-y-3 overflow-hidden pb-3">
    <Glow />
    <header className="relative z-10 flex flex-col gap-3 pt-2 md:flex-row md:items-end md:justify-between">
      <div><p className="text-xs font-semibold uppercase tracking-[.28em] text-emerald-300">Departments</p><h1 className="mt-2 text-3xl font-semibold leading-tight text-white md:text-4xl">Government Contract Activity</h1><p className="mt-2 text-sm leading-6 text-slate-300">Track department spending, contract awards, vendors, and public-company exposure.</p></div>
      {periodFilter}
    </header>
    <section className="relative z-10 grid gap-3 xl:grid-cols-[1.65fr_.9fr]">
      <Panel title="Government contract snapshot" subtitle={`Last ${data.period_days} days`} action="Live data"><TrendChart series={trends} /></Panel>
      <div className="grid gap-3 sm:grid-cols-2"><Snapshot label="Most active department" row={active} titleKeys={["name"]} valueKeys={["contract_value", "contracts"]} /><Snapshot label="Largest recent award" row={largest} titleKeys={["company", "symbol"]} valueKeys={["value"]} /><Snapshot label="Fastest growing vendor" row={growing} titleKeys={["company", "symbol"]} valueKeys={["increase_value"]} /><Snapshot label="Top sector exposure" row={topSector} titleKeys={["label"]} valueKeys={["percent"]} percent /></div>
    </section>
    {comparisonPaused ? <Panel title="Comparison coverage"><p className="text-sm leading-6 text-amber-100">{data.comparison?.message ?? "Prior-period deltas are paused until contract ingest coverage is comparable."}</p></Panel> : null}
    <MetricCards metrics={data.summary} comparison={comparison} />
    <section className="grid gap-3 xl:grid-cols-2">
      <DataTable title="Top departments by contract value" rows={data.top_departments} cta={{ href: "/departments", label: "View all departments" }} columns={[["name", "Department", "link"], ["contracts", "Contracts", "number"], ["contract_value", "Total value", "currency"], ["change_pct", `Vs ${comparison}`, "percent"]]} />
      <DataTable title="Top vendors" rows={data.top_vendors} cta={{ href: "/feed?mode=government_contracts", label: "View all vendors" }} columns={[["vendor", "Vendor", "link"], ["symbol", "Ticker"], ["contracts", "Contracts", "number"], ["contract_value", "Total value", "currency"], ["top_department", "Top department"]]} />
    </section>
    <section className="grid gap-3 xl:grid-cols-[1.15fr_1fr_.9fr]"><SectorMix rows={data.contract_value_over_time} /><SectorRanks rows={latestSectors} /><ContractMix contracts={contractMetric?.value} modifications={modificationMetric?.value} /></section>
    <section className="grid gap-3 xl:grid-cols-[.85fr_1.1fr_1.2fr]"><VendorMix rows={latestSectors} /><GrowingVendors rows={data.fastest_growing_vendors} /><DataTable title="Recent notable awards" rows={data.largest_recent_awards} cta={{ href: "/feed?mode=government_contracts", label: "View all awards" }} columns={[["department", "Department"], ["company", "Vendor", "link"], ["symbol", "Ticker"], ["value", "Value", "currency"], ["date", "Date", "date"]]} /></section>
    <Panel title="Contract value over time" subtitle="Mapped public-company vendor sectors; unclassified symbols are excluded."><TrendChart series={trends} bars /></Panel>
  </main>;
}

function Panel({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: ReactNode; children: ReactNode }) { return <section className="min-w-0 rounded-lg border border-slate-700/70 bg-slate-950/65 p-4 shadow-[0_18px_50px_rgba(0,0,0,.18)]"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-sm font-semibold uppercase tracking-[.15em] text-white">{title}</h2>{subtitle ? <p className="mt-1 text-xs text-slate-400">{subtitle}</p> : null}</div>{action ? <span className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">{action}</span> : null}</div><div className="mt-4">{children}</div></section>; }
function Snapshot({ label, row, titleKeys, valueKeys, percent = false }: { label: string; row?: Row; titleKeys: string[]; valueKeys: string[]; percent?: boolean }) { const title = row ? firstString(row, titleKeys) : null; const value = row ? firstValue(row, valueKeys) : null; return <div className="min-w-0 rounded-lg border border-slate-700/70 bg-slate-950/65 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-2 truncate text-sm font-semibold text-white">{title ?? "No current record"}</p><p className="mt-2 text-lg font-semibold tabular-nums text-emerald-300">{percent && typeof value === "number" ? `${value.toFixed(1)}%` : money(value)}</p></div>; }
function MetricCards({ metrics, comparison }: { metrics: ProfileMetric[]; comparison: string }) { return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map((metric) => <div key={metric.label} className="min-w-0 rounded-lg border border-slate-700/70 bg-slate-950/65 p-4"><p className="truncate text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">{metric.label}</p><p className="mt-3 truncate text-2xl font-semibold tabular-nums text-white">{metric.format === "currency" ? money(metric.value) : number(metric.value)}</p><p className={`mt-2 text-xs font-semibold ${typeof metric.change_pct === "number" ? metric.change_pct >= 0 ? "text-emerald-300" : "text-rose-300" : "text-slate-500"}`}>{typeof metric.change_pct === "number" ? `${metric.change_pct >= 0 ? "+" : ""}${metric.change_pct.toFixed(1)}% vs ${comparison}` : "Latest available period"}</p></div>)}</section>; }
function DataTable({ title, rows, columns, cta }: TableSpec) { return <Panel title={title}>{rows.length ? <div className="overflow-x-auto"><table className="min-w-[34rem] w-full text-left text-xs"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[.13em] text-slate-500"><tr>{columns.map(([, label]) => <th key={label} className="px-2 py-2.5 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-white/5">{rows.slice(0, 8).map((row, index) => <tr key={index}>{columns.map(([key, , format]) => <td key={key} className="max-w-40 truncate px-2 py-2.5 text-slate-300">{cell(row, key, format)}</td>)}</tr>)}</tbody></table></div> : <p className="py-8 text-sm text-slate-400">No database records are available for this selection.</p>}{cta ? <Link href={cta.href} className="mt-3 inline-flex text-xs font-semibold text-emerald-200 hover:text-emerald-100">{cta.label} -&gt;</Link> : null}</Panel>; }
function SectorMix({ rows }: { rows: ProfileSectorPeriod[] }) { const labels = sectors(rows); return <Panel title="Department spending mix over time" subtitle="Percent of mapped contract value"><div className="flex h-36 items-end gap-2">{rows.map((row) => <div key={row.period} className="flex h-full min-w-6 flex-1 flex-col-reverse overflow-hidden rounded-sm bg-slate-900">{ordered(row, labels).map((segment) => <span key={segment.label} title={`${segment.label}: ${segment.percent.toFixed(1)}%`} style={{ height: `${Math.max(segment.percent, 1)}%`, backgroundColor: color(segment.label, labels) }} />)}</div>)}</div><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1.5">{labels.slice(0, 8).map((label) => <span key={label} className="inline-flex items-center gap-1.5 text-[10px] text-slate-400"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: color(label, labels) }} />{label}</span>)}</div></Panel>; }
function SectorRanks({ rows }: { rows: Array<{ label: string; value: number; percent: number }> }) { const max = Math.max(...rows.map((row) => row.value), 1); return <Panel title="Contract value by sector"><div className="space-y-3">{rows.slice(0, 7).map((row, index) => <div key={row.label} className="grid grid-cols-[minmax(0,1fr)_3.75rem] items-center gap-3 text-xs"><span className="truncate text-slate-300">{row.label}</span><span className="text-right font-semibold text-emerald-300">{money(row.value)}</span><div className="col-span-2 h-2 overflow-hidden rounded-sm bg-slate-800"><div className="h-full rounded-sm" style={{ width: `${Math.max(3, row.value / max * 100)}%`, backgroundColor: COLORS[index % COLORS.length] }} /></div></div>)}</div></Panel>; }
function ContractMix({ contracts, modifications }: { contracts?: number | null; modifications?: number | null }) { const total = (contracts ?? 0) + (modifications ?? 0); return <Panel title="Contracts vs modifications"><Donut values={[contracts ?? 0, modifications ?? 0]} colors={["#42d3a7", "#3b82f6"]} value={number(total)} label="Total records" /><div className="mt-4 space-y-2"><Legend label="Contracts" value={number(contracts)} color="#42d3a7" /><Legend label="Modifications" value={number(modifications)} color="#3b82f6" /></div></Panel>; }
function VendorMix({ rows }: { rows: Array<{ label: string; value: number; percent: number }> }) { return <Panel title="Vendor mix by sector"><Donut values={rows.slice(0, 5).map((row) => row.value)} colors={rows.slice(0, 5).map((_, index) => COLORS[index])} value={rows[0] ? `${rows[0].percent.toFixed(1)}%` : "-"} label={rows[0]?.label ?? "No data"} /><div className="mt-4 space-y-2">{rows.slice(0, 5).map((row, index) => <Legend key={row.label} label={row.label} value={`${row.percent.toFixed(1)}%`} color={COLORS[index]} />)}</div></Panel>; }
function GrowingVendors({ rows }: { rows: Row[] }) { return <Panel title="Top moving vendors" subtitle="Value growth vs prior period"><div className="space-y-2.5">{rows.slice(0, 6).map((row, index) => <div key={index} className="grid grid-cols-[minmax(0,1fr)_4.5rem] gap-3 text-xs"><span className="truncate text-slate-300">{firstString(row, ["company", "symbol"]) ?? "-"}</span><span className="text-right font-semibold text-emerald-300">{money(firstValue(row, ["increase_value"]))}</span></div>)}</div></Panel>; }
function TrendChart({ series, bars = false }: { series: Array<{ label: string; value: number }>; bars?: boolean }) { if (!series.length) return <p className="flex h-40 items-center justify-center text-sm text-slate-400">No time-series records are available.</p>; const max = Math.max(...series.map((point) => point.value), 1); const points = series.map((point, index) => `${(index / Math.max(series.length - 1, 1)) * 100},${100 - point.value / max * 85}`).join(" "); return <div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-36 w-full overflow-visible"><defs><linearGradient id="government-trend" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#42d3a7" stopOpacity=".35"/><stop offset="1" stopColor="#42d3a7" stopOpacity="0"/></linearGradient></defs>{bars ? series.map((point, index) => <rect key={point.label} x={index / series.length * 100 + 1} y={100 - point.value / max * 75} width={Math.max(2, 90 / series.length)} height={point.value / max * 75} fill="#3b82f6" opacity=".65" />) : <><polyline points={`0,100 ${points} 100,100`} fill="url(#government-trend)" stroke="none"/><polyline points={points} fill="none" stroke="#55e3b0" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></>}</svg><div className="mt-2 flex justify-between text-[10px] text-slate-500"><span>{series[0].label}</span><span>{series[series.length - 1].label}</span></div></div>; }
function Donut({ values, colors, value, label }: { values: number[]; colors: string[]; value: string; label: string }) { const total = values.reduce((sum, item) => sum + item, 0); let offset = 0; return <div className="relative mx-auto h-36 w-36"><svg viewBox="0 0 42 42" className="h-full w-full -rotate-90">{values.map((item, index) => { const dash = total ? item / total * 100 : 0; const circle = <circle key={index} cx="21" cy="21" r="15.915" fill="none" stroke={colors[index]} strokeWidth="7" strokeDasharray={`${dash} ${100 - dash}`} strokeDashoffset={-offset} />; offset += dash; return circle; })}</svg><div className="absolute inset-0 flex flex-col items-center justify-center"><b className="text-lg text-white">{value}</b><span className="max-w-20 text-center text-[9px] uppercase tracking-[.12em] text-slate-500">{label}</span></div></div>; }
function Legend({ label, value, color }: { label: string; value: string; color: string }) { return <div className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 truncate text-slate-300"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: color }} />{label}</span><span className="font-semibold tabular-nums text-white">{value}</span></div>; }
function findMetric(metrics: ProfileMetric[], label: string) { return metrics.find((metric) => metric.label === label); }
function sectors(rows: ProfileSectorPeriod[]) { const latest = rows[rows.length - 1]?.segments.map((segment) => segment.label) ?? []; return [...latest, ...Array.from(new Set(rows.flatMap((row) => row.segments.map((segment) => segment.label)))).filter((label) => !latest.includes(label))]; }
function ordered(row: ProfileSectorPeriod, labels: string[]) { const indexed = new Map(row.segments.map((segment) => [segment.label, segment])); return labels.map((label) => indexed.get(label)).filter((segment): segment is NonNullable<typeof segment> => Boolean(segment)); }
function color(label: string, labels: string[]) { return COLORS[Math.max(labels.indexOf(label), 0) % COLORS.length]; }
function cell(row: Row, key: string, format?: CellFormat) { const value = row[key]; if (format === "link") { const href = typeof row.href === "string" ? row.href : null; return href ? <Link href={href} prefetch={false} className="font-semibold text-emerald-200 hover:text-emerald-100">{String(value ?? "-")}</Link> : <span className="font-semibold text-emerald-200">{String(value ?? "-")}</span>; } if (format === "currency") return money(asNumber(value)); if (format === "number") return number(asNumber(value)); if (format === "percent") return typeof value === "number" ? `${value >= 0 ? "+" : ""}${value.toFixed(1)}%` : "-"; if (format === "date") return typeof value === "string" ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "-"; return String(value ?? "-"); }
function firstString(row: Row, keys: string[]) { for (const key of keys) if (typeof row[key] === "string" && row[key]) return row[key] as string; return null; }
function firstValue(row: Row, keys: string[]) { for (const key of keys) if (typeof row[key] === "number") return row[key] as number; return null; }
function asNumber(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value : null; }
function money(value?: number | null) { return typeof value === "number" && Number.isFinite(value) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(value) : "-"; }
function number(value?: number | null) { return typeof value === "number" && Number.isFinite(value) ? new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value) : "-"; }
function Glow() { return <div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-48 opacity-60 [background:radial-gradient(ellipse_at_70%_0%,rgba(52,211,153,.16),transparent_38%),radial-gradient(ellipse_at_25%_0%,rgba(59,130,246,.11),transparent_44%)]" />; }
